version: '3.8'

services:
  x-postgres:
    hostname: ${POSTGRES_HOST}
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      PGUSER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_DATABASE_USERNAME: ${POSTGRES_DATABASE_USERNAME}
      POSTGRES_DATABASE_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/volumes/postgres:/home/postgres/pgdata/data
      - ./docker/scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    networks:
      - xnetwork
    restart: unless-stopped
    mem_limit: 300m
    mem_reservation: 200m

networks:
  xnetwork:
    external: true
